[package]
name = "ananse"
description = "Ananse: A WebAssembly-native zero-knowledge virtual machine (zkVM)"
keywords = ["wasm", "zero-knowledge", "zk", "zkvm", "stark"]
categories = ["compilers", "cryptography", "wasm"]
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"

[lib]
name = "ananse"
path = "src/lib.rs"

[[bin]]
name = "ananse"
path = "src/main.rs"

[dependencies]
ananse_decoder = { workspace = true }
ananse_lift = { workspace = true }
ananse_executor = { workspace = true }
ananse_trace = { workspace = true }
ananse_air = { workspace = true }
ananse_wasi = { workspace = true }

clap = { workspace = true }
thiserror = { workspace = true, features = ["std"] }
wat.workspace = true
