[workspace]
resolver = "2"
members = [
    "crates/ananse",
    "crates/ananse_decoder",
    "crates/ananse_lift",
    "crates/ananse_executor",
    "crates/ananse_trace",
    "crates/ananse_air",
    "crates/ananse_wasi",
    "tests",
]
default-members = ["crates/ananse"]

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.89"
license = "MIT OR Apache-2.0"
repository = "https://github.com/maatlabs/ananse"
homepage = "https://github.com/maatlabs/ananse"
readme = "README.md"

[workspace.dependencies]
ananse_decoder = { path = "crates/ananse_decoder", version = "0.2.0" }
ananse_lift = { path = "crates/ananse_lift", version = "0.2.0" }
ananse_executor = { path = "crates/ananse_executor", version = "0.2.0" }
ananse_trace = { path = "crates/ananse_trace", version = "0.2.0" }
ananse_air = { path = "crates/ananse_air", version = "0.2.0" }
ananse_wasi = { path = "crates/ananse_wasi", version = "0.2.0" }

p3-field = "0.6"
p3-goldilocks = "0.6"
p3-air = "0.6"
p3-matrix = "0.6"
clap = { version = "4.6", features = ["derive"] }
thiserror = { version = "2", default-features = false }
wasmparser = { version = "0.252", default-features = false, features = [
    "validate",
    "features",
] }
wat = "1.252"
