[package]
name = "ananse_tests"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
publish = false

[dependencies]
ananse_decoder = { workspace = true }
ananse_lift = { workspace = true }
ananse_executor = { workspace = true }
ananse_trace = { workspace = true }

maat_field = { workspace = true }
wasmparser = { workspace = true }
wat.workspace = true
