[package]
name = "mvm_tests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
mvm_decoder = { workspace = true }
mvm_lift = { workspace = true }
mvm_executor = { workspace = true }

maat_field = { workspace = true }
wasmparser = { workspace = true }
wat.workspace = true
