use wasmparser::Operator;

use crate::{DecodeError, Result};

/// The identity of a WebAssembly operator, stripped of its immediate operands.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[allow(missing_docs)]
pub enum OpCode {
    Unreachable,
    Nop,
    Block,
    Loop,
    If,
    Else,
    End,
    Br,
    BrIf,
    BrTable,
    Return,
    Call,
    Drop,
    Select,

    LocalGet,
    LocalSet,
    LocalTee,
    GlobalGet,
    GlobalSet,

    I32Const,
    I64Const,

    I32Load,
    I64Load,
    I32Load8S,
    I32Load8U,
    I32Load16S,
    I32Load16U,
    I64Load8S,
    I64Load8U,
    I64Load16S,
    I64Load16U,
    I64Load32S,
    I64Load32U,
    I32Store,
    I64Store,
    I32Store8,
    I32Store16,
    I64Store8,
    I64Store16,
    I64Store32,
    MemorySize,
    MemoryGrow,

    I32Eqz,
    I32Eq,
    I32Ne,
    I32LtS,
    I32LtU,
    I32GtS,
    I32GtU,
    I32LeS,
    I32LeU,
    I32GeS,
    I32GeU,
    I64Eqz,
    I64Eq,
    I64Ne,
    I64LtS,
    I64LtU,
    I64GtS,
    I64GtU,
    I64LeS,
    I64LeU,
    I64GeS,
    I64GeU,

    I32Clz,
    I32Ctz,
    I32Popcnt,
    I32Add,
    I32Sub,
    I32Mul,
    I32DivS,
    I32DivU,
    I32RemS,
    I32RemU,
    I32And,
    I32Or,
    I32Xor,
    I32Shl,
    I32ShrS,
    I32ShrU,
    I32Rotl,
    I32Rotr,
    I64Clz,
    I64Ctz,
    I64Popcnt,
    I64Add,
    I64Sub,
    I64Mul,
    I64DivS,
    I64DivU,
    I64RemS,
    I64RemU,
    I64And,
    I64Or,
    I64Xor,
    I64Shl,
    I64ShrS,
    I64ShrU,
    I64Rotl,
    I64Rotr,

    I32WrapI64,
    I64ExtendI32S,
    I64ExtendI32U,
}

impl OpCode {
    /// Maps a WebAssembly instruction (i.e., a validated [Operator]) onto its
    /// corresponding [`OpCode`].
    pub fn from_operator(op: &Operator) -> Result<OpCode> {
        let opcode = match op {
            Operator::Unreachable => OpCode::Unreachable,
            Operator::Nop => OpCode::Nop,
            Operator::Block { .. } => OpCode::Block,
            Operator::Loop { .. } => OpCode::Loop,
            Operator::If { .. } => OpCode::If,
            Operator::Else => OpCode::Else,
            Operator::End => OpCode::End,
            Operator::Br { .. } => OpCode::Br,
            Operator::BrIf { .. } => OpCode::BrIf,
            Operator::BrTable { .. } => OpCode::BrTable,
            Operator::Return => OpCode::Return,
            Operator::Call { .. } => OpCode::Call,
            Operator::Drop => OpCode::Drop,
            Operator::Select => OpCode::Select,
            Operator::LocalGet { .. } => OpCode::LocalGet,
            Operator::LocalSet { .. } => OpCode::LocalSet,
            Operator::LocalTee { .. } => OpCode::LocalTee,
            Operator::GlobalGet { .. } => OpCode::GlobalGet,
            Operator::GlobalSet { .. } => OpCode::GlobalSet,
            Operator::I32Const { .. } => OpCode::I32Const,
            Operator::I64Const { .. } => OpCode::I64Const,
            Operator::I32Load { .. } => OpCode::I32Load,
            Operator::I64Load { .. } => OpCode::I64Load,
            Operator::I32Load8S { .. } => OpCode::I32Load8S,
            Operator::I32Load8U { .. } => OpCode::I32Load8U,
            Operator::I32Load16S { .. } => OpCode::I32Load16S,
            Operator::I32Load16U { .. } => OpCode::I32Load16U,
            Operator::I64Load8S { .. } => OpCode::I64Load8S,
            Operator::I64Load8U { .. } => OpCode::I64Load8U,
            Operator::I64Load16S { .. } => OpCode::I64Load16S,
            Operator::I64Load16U { .. } => OpCode::I64Load16U,
            Operator::I64Load32S { .. } => OpCode::I64Load32S,
            Operator::I64Load32U { .. } => OpCode::I64Load32U,
            Operator::I32Store { .. } => OpCode::I32Store,
            Operator::I64Store { .. } => OpCode::I64Store,
            Operator::I32Store8 { .. } => OpCode::I32Store8,
            Operator::I32Store16 { .. } => OpCode::I32Store16,
            Operator::I64Store8 { .. } => OpCode::I64Store8,
            Operator::I64Store16 { .. } => OpCode::I64Store16,
            Operator::I64Store32 { .. } => OpCode::I64Store32,
            Operator::MemorySize { .. } => OpCode::MemorySize,
            Operator::MemoryGrow { .. } => OpCode::MemoryGrow,
            Operator::I32Eqz => OpCode::I32Eqz,
            Operator::I32Eq => OpCode::I32Eq,
            Operator::I32Ne => OpCode::I32Ne,
            Operator::I32LtS => OpCode::I32LtS,
            Operator::I32LtU => OpCode::I32LtU,
            Operator::I32GtS => OpCode::I32GtS,
            Operator::I32GtU => OpCode::I32GtU,
            Operator::I32LeS => OpCode::I32LeS,
            Operator::I32LeU => OpCode::I32LeU,
            Operator::I32GeS => OpCode::I32GeS,
            Operator::I32GeU => OpCode::I32GeU,
            Operator::I64Eqz => OpCode::I64Eqz,
            Operator::I64Eq => OpCode::I64Eq,
            Operator::I64Ne => OpCode::I64Ne,
            Operator::I64LtS => OpCode::I64LtS,
            Operator::I64LtU => OpCode::I64LtU,
            Operator::I64GtS => OpCode::I64GtS,
            Operator::I64GtU => OpCode::I64GtU,
            Operator::I64LeS => OpCode::I64LeS,
            Operator::I64LeU => OpCode::I64LeU,
            Operator::I64GeS => OpCode::I64GeS,
            Operator::I64GeU => OpCode::I64GeU,
            Operator::I32Clz => OpCode::I32Clz,
            Operator::I32Ctz => OpCode::I32Ctz,
            Operator::I32Popcnt => OpCode::I32Popcnt,
            Operator::I32Add => OpCode::I32Add,
            Operator::I32Sub => OpCode::I32Sub,
            Operator::I32Mul => OpCode::I32Mul,
            Operator::I32DivS => OpCode::I32DivS,
            Operator::I32DivU => OpCode::I32DivU,
            Operator::I32RemS => OpCode::I32RemS,
            Operator::I32RemU => OpCode::I32RemU,
            Operator::I32And => OpCode::I32And,
            Operator::I32Or => OpCode::I32Or,
            Operator::I32Xor => OpCode::I32Xor,
            Operator::I32Shl => OpCode::I32Shl,
            Operator::I32ShrS => OpCode::I32ShrS,
            Operator::I32ShrU => OpCode::I32ShrU,
            Operator::I32Rotl => OpCode::I32Rotl,
            Operator::I32Rotr => OpCode::I32Rotr,
            Operator::I64Clz => OpCode::I64Clz,
            Operator::I64Ctz => OpCode::I64Ctz,
            Operator::I64Popcnt => OpCode::I64Popcnt,
            Operator::I64Add => OpCode::I64Add,
            Operator::I64Sub => OpCode::I64Sub,
            Operator::I64Mul => OpCode::I64Mul,
            Operator::I64DivS => OpCode::I64DivS,
            Operator::I64DivU => OpCode::I64DivU,
            Operator::I64RemS => OpCode::I64RemS,
            Operator::I64RemU => OpCode::I64RemU,
            Operator::I64And => OpCode::I64And,
            Operator::I64Or => OpCode::I64Or,
            Operator::I64Xor => OpCode::I64Xor,
            Operator::I64Shl => OpCode::I64Shl,
            Operator::I64ShrS => OpCode::I64ShrS,
            Operator::I64ShrU => OpCode::I64ShrU,
            Operator::I64Rotl => OpCode::I64Rotl,
            Operator::I64Rotr => OpCode::I64Rotr,
            Operator::I32WrapI64 => OpCode::I32WrapI64,
            Operator::I64ExtendI32S => OpCode::I64ExtendI32S,
            Operator::I64ExtendI32U => OpCode::I64ExtendI32U,
            other => {
                return Err(DecodeError::UnsupportedOperator {
                    offset: 0,
                    operator: format!("{other:?}"),
                });
            }
        };

        Ok(opcode)
    }
}
