use crate::{DecodeError, Instruction, Result};

/// The identity of a WebAssembly instruction, stripped of its immediate operands.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[allow(missing_docs)]
pub enum OpCode {
    Unreachable,
    Nop,
    Block,
    Loop,
    If,
    Else,
    End,
    Br,
    BrIf,
    BrTable,
    Return,
    Call,
    Drop,
    Select,

    LocalGet,
    LocalSet,
    LocalTee,
    GlobalGet,
    GlobalSet,

    I32Const,
    I64Const,

    I32Load,
    I64Load,
    I32Load8S,
    I32Load8U,
    I32Load16S,
    I32Load16U,
    I64Load8S,
    I64Load8U,
    I64Load16S,
    I64Load16U,
    I64Load32S,
    I64Load32U,
    I32Store,
    I64Store,
    I32Store8,
    I32Store16,
    I64Store8,
    I64Store16,
    I64Store32,
    MemorySize,
    MemoryGrow,

    I32Eqz,
    I32Eq,
    I32Ne,
    I32LtS,
    I32LtU,
    I32GtS,
    I32GtU,
    I32LeS,
    I32LeU,
    I32GeS,
    I32GeU,
    I64Eqz,
    I64Eq,
    I64Ne,
    I64LtS,
    I64LtU,
    I64GtS,
    I64GtU,
    I64LeS,
    I64LeU,
    I64GeS,
    I64GeU,

    I32Clz,
    I32Ctz,
    I32Popcnt,
    I32Add,
    I32Sub,
    I32Mul,
    I32DivS,
    I32DivU,
    I32RemS,
    I32RemU,
    I32And,
    I32Or,
    I32Xor,
    I32Shl,
    I32ShrS,
    I32ShrU,
    I32Rotl,
    I32Rotr,
    I64Clz,
    I64Ctz,
    I64Popcnt,
    I64Add,
    I64Sub,
    I64Mul,
    I64DivS,
    I64DivU,
    I64RemS,
    I64RemU,
    I64And,
    I64Or,
    I64Xor,
    I64Shl,
    I64ShrS,
    I64ShrU,
    I64Rotl,
    I64Rotr,

    I32WrapI64,
    I64ExtendI32S,
    I64ExtendI32U,
}

impl OpCode {
    /// Maps a WebAssembly [Instruction] onto its corresponding [`OpCode`].
    pub fn from_instruction(i: &Instruction) -> Result<Self> {
        let opcode = match i {
            Instruction::Unreachable => Self::Unreachable,
            Instruction::Nop => Self::Nop,
            Instruction::Block { .. } => Self::Block,
            Instruction::Loop { .. } => Self::Loop,
            Instruction::If { .. } => Self::If,
            Instruction::Else => Self::Else,
            Instruction::End => Self::End,
            Instruction::Br { .. } => Self::Br,
            Instruction::BrIf { .. } => Self::BrIf,
            Instruction::BrTable { .. } => Self::BrTable,
            Instruction::Return => Self::Return,
            Instruction::Call { .. } => Self::Call,
            Instruction::Drop => Self::Drop,
            Instruction::Select => Self::Select,
            Instruction::LocalGet { .. } => Self::LocalGet,
            Instruction::LocalSet { .. } => Self::LocalSet,
            Instruction::LocalTee { .. } => Self::LocalTee,
            Instruction::GlobalGet { .. } => Self::GlobalGet,
            Instruction::GlobalSet { .. } => Self::GlobalSet,
            Instruction::I32Const { .. } => Self::I32Const,
            Instruction::I64Const { .. } => Self::I64Const,
            Instruction::I32Load { .. } => Self::I32Load,
            Instruction::I64Load { .. } => Self::I64Load,
            Instruction::I32Load8S { .. } => Self::I32Load8S,
            Instruction::I32Load8U { .. } => Self::I32Load8U,
            Instruction::I32Load16S { .. } => Self::I32Load16S,
            Instruction::I32Load16U { .. } => Self::I32Load16U,
            Instruction::I64Load8S { .. } => Self::I64Load8S,
            Instruction::I64Load8U { .. } => Self::I64Load8U,
            Instruction::I64Load16S { .. } => Self::I64Load16S,
            Instruction::I64Load16U { .. } => Self::I64Load16U,
            Instruction::I64Load32S { .. } => Self::I64Load32S,
            Instruction::I64Load32U { .. } => Self::I64Load32U,
            Instruction::I32Store { .. } => Self::I32Store,
            Instruction::I64Store { .. } => Self::I64Store,
            Instruction::I32Store8 { .. } => Self::I32Store8,
            Instruction::I32Store16 { .. } => Self::I32Store16,
            Instruction::I64Store8 { .. } => Self::I64Store8,
            Instruction::I64Store16 { .. } => Self::I64Store16,
            Instruction::I64Store32 { .. } => Self::I64Store32,
            Instruction::MemorySize { .. } => Self::MemorySize,
            Instruction::MemoryGrow { .. } => Self::MemoryGrow,
            Instruction::I32Eqz => Self::I32Eqz,
            Instruction::I32Eq => Self::I32Eq,
            Instruction::I32Ne => Self::I32Ne,
            Instruction::I32LtS => Self::I32LtS,
            Instruction::I32LtU => Self::I32LtU,
            Instruction::I32GtS => Self::I32GtS,
            Instruction::I32GtU => Self::I32GtU,
            Instruction::I32LeS => Self::I32LeS,
            Instruction::I32LeU => Self::I32LeU,
            Instruction::I32GeS => Self::I32GeS,
            Instruction::I32GeU => Self::I32GeU,
            Instruction::I64Eqz => Self::I64Eqz,
            Instruction::I64Eq => Self::I64Eq,
            Instruction::I64Ne => Self::I64Ne,
            Instruction::I64LtS => Self::I64LtS,
            Instruction::I64LtU => Self::I64LtU,
            Instruction::I64GtS => Self::I64GtS,
            Instruction::I64GtU => Self::I64GtU,
            Instruction::I64LeS => Self::I64LeS,
            Instruction::I64LeU => Self::I64LeU,
            Instruction::I64GeS => Self::I64GeS,
            Instruction::I64GeU => Self::I64GeU,
            Instruction::I32Clz => Self::I32Clz,
            Instruction::I32Ctz => Self::I32Ctz,
            Instruction::I32Popcnt => Self::I32Popcnt,
            Instruction::I32Add => Self::I32Add,
            Instruction::I32Sub => Self::I32Sub,
            Instruction::I32Mul => Self::I32Mul,
            Instruction::I32DivS => Self::I32DivS,
            Instruction::I32DivU => Self::I32DivU,
            Instruction::I32RemS => Self::I32RemS,
            Instruction::I32RemU => Self::I32RemU,
            Instruction::I32And => Self::I32And,
            Instruction::I32Or => Self::I32Or,
            Instruction::I32Xor => Self::I32Xor,
            Instruction::I32Shl => Self::I32Shl,
            Instruction::I32ShrS => Self::I32ShrS,
            Instruction::I32ShrU => Self::I32ShrU,
            Instruction::I32Rotl => Self::I32Rotl,
            Instruction::I32Rotr => Self::I32Rotr,
            Instruction::I64Clz => Self::I64Clz,
            Instruction::I64Ctz => Self::I64Ctz,
            Instruction::I64Popcnt => Self::I64Popcnt,
            Instruction::I64Add => Self::I64Add,
            Instruction::I64Sub => Self::I64Sub,
            Instruction::I64Mul => Self::I64Mul,
            Instruction::I64DivS => Self::I64DivS,
            Instruction::I64DivU => Self::I64DivU,
            Instruction::I64RemS => Self::I64RemS,
            Instruction::I64RemU => Self::I64RemU,
            Instruction::I64And => Self::I64And,
            Instruction::I64Or => Self::I64Or,
            Instruction::I64Xor => Self::I64Xor,
            Instruction::I64Shl => Self::I64Shl,
            Instruction::I64ShrS => Self::I64ShrS,
            Instruction::I64ShrU => Self::I64ShrU,
            Instruction::I64Rotl => Self::I64Rotl,
            Instruction::I64Rotr => Self::I64Rotr,
            Instruction::I32WrapI64 => Self::I32WrapI64,
            Instruction::I64ExtendI32S => Self::I64ExtendI32S,
            Instruction::I64ExtendI32U => Self::I64ExtendI32U,
            other => {
                return Err(DecodeError::UnsupportedOperator {
                    offset: 0,
                    operator: format!("{other:?}"),
                });
            }
        };

        Ok(opcode)
    }

    pub fn load_shape(&self) -> (usize, bool, bool) {
        match self {
            Self::I32Load => (4, false, false),
            Self::I64Load => (8, false, true),
            Self::I32Load8S => (1, true, false),
            Self::I32Load8U => (1, false, false),
            Self::I32Load16S => (2, true, false),
            Self::I32Load16U => (2, false, false),
            Self::I64Load8S => (1, true, true),
            Self::I64Load8U => (1, false, true),
            Self::I64Load16S => (2, true, true),
            Self::I64Load16U => (2, false, true),
            Self::I64Load32S => (4, true, true),
            Self::I64Load32U => (4, false, true),
            _ => (0, false, false),
        }
    }
}
