use crate::{DecodeError, Instruction, Result};

/// The identity of a WebAssembly instruction, stripped of its immediate operands.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[allow(missing_docs)]
pub enum OpCode {
    Unreachable,
    Nop,
    Block,
    Loop,
    If,
    Else,
    End,
    Br,
    BrIf,
    BrTable,
    Return,
    Call,
    Drop,
    Select,

    LocalGet,
    LocalSet,
    LocalTee,
    GlobalGet,
    GlobalSet,

    I32Const,
    I64Const,

    I32Load,
    I64Load,
    I32Load8S,
    I32Load8U,
    I32Load16S,
    I32Load16U,
    I64Load8S,
    I64Load8U,
    I64Load16S,
    I64Load16U,
    I64Load32S,
    I64Load32U,
    I32Store,
    I64Store,
    I32Store8,
    I32Store16,
    I64Store8,
    I64Store16,
    I64Store32,
    MemorySize,
    MemoryGrow,

    I32Eqz,
    I32Eq,
    I32Ne,
    I32LtS,
    I32LtU,
    I32GtS,
    I32GtU,
    I32LeS,
    I32LeU,
    I32GeS,
    I32GeU,
    I64Eqz,
    I64Eq,
    I64Ne,
    I64LtS,
    I64LtU,
    I64GtS,
    I64GtU,
    I64LeS,
    I64LeU,
    I64GeS,
    I64GeU,

    I32Clz,
    I32Ctz,
    I32Popcnt,
    I32Add,
    I32Sub,
    I32Mul,
    I32DivS,
    I32DivU,
    I32RemS,
    I32RemU,
    I32And,
    I32Or,
    I32Xor,
    I32Shl,
    I32ShrS,
    I32ShrU,
    I32Rotl,
    I32Rotr,
    I64Clz,
    I64Ctz,
    I64Popcnt,
    I64Add,
    I64Sub,
    I64Mul,
    I64DivS,
    I64DivU,
    I64RemS,
    I64RemU,
    I64And,
    I64Or,
    I64Xor,
    I64Shl,
    I64ShrS,
    I64ShrU,
    I64Rotl,
    I64Rotr,

    I32WrapI64,
    I64ExtendI32S,
    I64ExtendI32U,
}

impl OpCode {
    /// Maps a WebAssembly [Instruction] onto its corresponding [`OpCode`].
    pub fn from_instruction(i: &Instruction) -> Result<OpCode> {
        let opcode = match i {
            Instruction::Unreachable => OpCode::Unreachable,
            Instruction::Nop => OpCode::Nop,
            Instruction::Block { .. } => OpCode::Block,
            Instruction::Loop { .. } => OpCode::Loop,
            Instruction::If { .. } => OpCode::If,
            Instruction::Else => OpCode::Else,
            Instruction::End => OpCode::End,
            Instruction::Br { .. } => OpCode::Br,
            Instruction::BrIf { .. } => OpCode::BrIf,
            Instruction::BrTable { .. } => OpCode::BrTable,
            Instruction::Return => OpCode::Return,
            Instruction::Call { .. } => OpCode::Call,
            Instruction::Drop => OpCode::Drop,
            Instruction::Select => OpCode::Select,
            Instruction::LocalGet { .. } => OpCode::LocalGet,
            Instruction::LocalSet { .. } => OpCode::LocalSet,
            Instruction::LocalTee { .. } => OpCode::LocalTee,
            Instruction::GlobalGet { .. } => OpCode::GlobalGet,
            Instruction::GlobalSet { .. } => OpCode::GlobalSet,
            Instruction::I32Const { .. } => OpCode::I32Const,
            Instruction::I64Const { .. } => OpCode::I64Const,
            Instruction::I32Load { .. } => OpCode::I32Load,
            Instruction::I64Load { .. } => OpCode::I64Load,
            Instruction::I32Load8S { .. } => OpCode::I32Load8S,
            Instruction::I32Load8U { .. } => OpCode::I32Load8U,
            Instruction::I32Load16S { .. } => OpCode::I32Load16S,
            Instruction::I32Load16U { .. } => OpCode::I32Load16U,
            Instruction::I64Load8S { .. } => OpCode::I64Load8S,
            Instruction::I64Load8U { .. } => OpCode::I64Load8U,
            Instruction::I64Load16S { .. } => OpCode::I64Load16S,
            Instruction::I64Load16U { .. } => OpCode::I64Load16U,
            Instruction::I64Load32S { .. } => OpCode::I64Load32S,
            Instruction::I64Load32U { .. } => OpCode::I64Load32U,
            Instruction::I32Store { .. } => OpCode::I32Store,
            Instruction::I64Store { .. } => OpCode::I64Store,
            Instruction::I32Store8 { .. } => OpCode::I32Store8,
            Instruction::I32Store16 { .. } => OpCode::I32Store16,
            Instruction::I64Store8 { .. } => OpCode::I64Store8,
            Instruction::I64Store16 { .. } => OpCode::I64Store16,
            Instruction::I64Store32 { .. } => OpCode::I64Store32,
            Instruction::MemorySize { .. } => OpCode::MemorySize,
            Instruction::MemoryGrow { .. } => OpCode::MemoryGrow,
            Instruction::I32Eqz => OpCode::I32Eqz,
            Instruction::I32Eq => OpCode::I32Eq,
            Instruction::I32Ne => OpCode::I32Ne,
            Instruction::I32LtS => OpCode::I32LtS,
            Instruction::I32LtU => OpCode::I32LtU,
            Instruction::I32GtS => OpCode::I32GtS,
            Instruction::I32GtU => OpCode::I32GtU,
            Instruction::I32LeS => OpCode::I32LeS,
            Instruction::I32LeU => OpCode::I32LeU,
            Instruction::I32GeS => OpCode::I32GeS,
            Instruction::I32GeU => OpCode::I32GeU,
            Instruction::I64Eqz => OpCode::I64Eqz,
            Instruction::I64Eq => OpCode::I64Eq,
            Instruction::I64Ne => OpCode::I64Ne,
            Instruction::I64LtS => OpCode::I64LtS,
            Instruction::I64LtU => OpCode::I64LtU,
            Instruction::I64GtS => OpCode::I64GtS,
            Instruction::I64GtU => OpCode::I64GtU,
            Instruction::I64LeS => OpCode::I64LeS,
            Instruction::I64LeU => OpCode::I64LeU,
            Instruction::I64GeS => OpCode::I64GeS,
            Instruction::I64GeU => OpCode::I64GeU,
            Instruction::I32Clz => OpCode::I32Clz,
            Instruction::I32Ctz => OpCode::I32Ctz,
            Instruction::I32Popcnt => OpCode::I32Popcnt,
            Instruction::I32Add => OpCode::I32Add,
            Instruction::I32Sub => OpCode::I32Sub,
            Instruction::I32Mul => OpCode::I32Mul,
            Instruction::I32DivS => OpCode::I32DivS,
            Instruction::I32DivU => OpCode::I32DivU,
            Instruction::I32RemS => OpCode::I32RemS,
            Instruction::I32RemU => OpCode::I32RemU,
            Instruction::I32And => OpCode::I32And,
            Instruction::I32Or => OpCode::I32Or,
            Instruction::I32Xor => OpCode::I32Xor,
            Instruction::I32Shl => OpCode::I32Shl,
            Instruction::I32ShrS => OpCode::I32ShrS,
            Instruction::I32ShrU => OpCode::I32ShrU,
            Instruction::I32Rotl => OpCode::I32Rotl,
            Instruction::I32Rotr => OpCode::I32Rotr,
            Instruction::I64Clz => OpCode::I64Clz,
            Instruction::I64Ctz => OpCode::I64Ctz,
            Instruction::I64Popcnt => OpCode::I64Popcnt,
            Instruction::I64Add => OpCode::I64Add,
            Instruction::I64Sub => OpCode::I64Sub,
            Instruction::I64Mul => OpCode::I64Mul,
            Instruction::I64DivS => OpCode::I64DivS,
            Instruction::I64DivU => OpCode::I64DivU,
            Instruction::I64RemS => OpCode::I64RemS,
            Instruction::I64RemU => OpCode::I64RemU,
            Instruction::I64And => OpCode::I64And,
            Instruction::I64Or => OpCode::I64Or,
            Instruction::I64Xor => OpCode::I64Xor,
            Instruction::I64Shl => OpCode::I64Shl,
            Instruction::I64ShrS => OpCode::I64ShrS,
            Instruction::I64ShrU => OpCode::I64ShrU,
            Instruction::I64Rotl => OpCode::I64Rotl,
            Instruction::I64Rotr => OpCode::I64Rotr,
            Instruction::I32WrapI64 => OpCode::I32WrapI64,
            Instruction::I64ExtendI32S => OpCode::I64ExtendI32S,
            Instruction::I64ExtendI32U => OpCode::I64ExtendI32U,
            other => {
                return Err(DecodeError::UnsupportedOperator {
                    offset: 0,
                    operator: format!("{other:?}"),
                });
            }
        };

        Ok(opcode)
    }
}
